pandoc Assignment1.md \
  -o Assignment1.pdf \
  --from markdown \
  --template eisvogel \
  --listings \
  --toc \
  -V toc-own-page=true \
  -V title="Assignment 1" \
  -V subtitle="Distributed Systems" \
  -V titlepage=true \
  -V papersize=a4 \
  -V fontsize=12pt \
  -V author="Abdulaziz Askar" \
  -V lang=en \
  -V colorlinks=true \
  -V geometry="margin=1in" \
  -V mainfont="Times New Roman" \
  -V sansfont="Times New Roman" \
  -V monofont="Times New Roman" \
  -V fontfamily="times" \
  -V caption-justification=centering \
  -V block-headings=true